CREATE TABLE MARKS(MARKID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(20),TOTAL INT,PER INT);
CREATE TRIGGER MARK_TRIGGER AFTER INSERT ON STUDENTINFO FOR EACH ROW  
INSERT INTO MARKS(NAME,TOTAL,per) VALUES(new.NAME,new.TOTAL,new.per);
INSERT INTO STUDENTINFO(ID,NAME,SUBJ1,SUBJ2,subj3)values(1002,'jan',35,42,43),(1003,'moon',44,38,48);
SELECT *FROM MARKS;