CREATE DATABASE TRIGER;
USE TRIGER;
CREATE TABLE STUDENTINFO(ID INT PRIMARY KEY , NAME VARCHAR(20) NOT NULL, SUBJ1 INT,SUBJ2 INT,SUBJ3 INT,TOTAL INT,PER INT);
CREATE TRIGGER MARKCHANGE BEFORE INSERT ON STUDENTINFO FOR EACH ROW SET new.total=new.SUBJ1+new.SUBJ2+NEW.SUBJ3,NEW.PER=NEW.TOTAL * 60/100;
insert into studentinfo(ID,NAME,SUBJ1,SUBJ2,SUBJ3) VALUES(101,'ABCD',34,45,49);
